In [1]:
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec

# Wave number one: $p_g = 3 p_{rad}$

In [2]:
import numpy as np

from geodesic_angular_grid import make_geodesic_angular_grid, geodesic_grid_summary
from radiative_dispersion import DispersionBackground, solve_dispersion_relation
from radiative_dispersion_directions import directional_mode_table, directional_mode_dict
from radiative_dispersion_isotropy import (
    print_background_comoving_isotropy_report,
    print_mode_comoving_isotropy_report,
)

grid = make_geodesic_angular_grid(generation=2)
print(geodesic_grid_summary(grid))

bg = DispersionBackground.from_parameters(
    rho0=1.0,
    temperature0=0.1,
    gamma_ad=5.0 / 3.0,
    absorption_opacity=10.0,
    scattering_opacity=10.0,
    erad0=0.1,
    grid=grid,
    arad=0.1/(0.1**4.0),
    require_thermal_equilibrium=True,
)

sol = solve_dispersion_relation(bg, k=2.0 * np.pi, normalize_to="rho1")
#sol.modes[0].omega
#print_mode_comoving_isotropy_report(sol.modes[30], bg, background_u1=0.0)

{'generation': 2, 'n_directions': 162, 'n_pentagons': 12, 'n_hexagons': 150, 'total_solid_angle': 12.566370614359307, 'min_solid_angle': 0.06929172492240787, 'max_solid_angle': 0.08227110788505243}


In [3]:
#print_mode_comoving_isotropy_report(sol.modes[86], bg, background_u1=0.0)

In [4]:
for i in range(len(sol.modes)):
    mode = sol.modes[i]
    if ( np.abs( np.imag(mode.omega) ) < 8 ):
        print("Wave Id = ", i, "Mode.omega = ", np.real(mode.omega), np.imag(mode.omega) )

Wave Id =  50 Mode.omega =  -2.3784029440446575 -0.08095364289349759
Wave Id =  84 Mode.omega =  4.600824653871707e-15 -0.23895695033249767
Wave Id =  114 Mode.omega =  2.378402944044663 -0.08095364289346098


In [5]:
#Properties of the sound wave:
mode = sol.modes[114]
mode.omega, mode.rho1, mode.p1, mode.v1, mode.erad1, mode.frad1

((2.378402944044663-0.08095364289346098j),
 (1+0j),
 (0.1422615116517316-0.0071474281369683715j),
 (0.37853458520902483-0.01288417242779044j),
 (0.16679247991900506-0.019796127115514293j),
 (0.04888623959635659-0.013229164617058642j))

In [6]:
np.imag(sol.modes[114].intensity1)

array([-3.26358809e-04, -3.26358809e-04, -5.68785164e-03, -3.06120227e-03,
        2.73958199e-04, -3.22384631e-04, -3.26358809e-04, -3.22384631e-04,
        2.73958199e-04, -3.06120227e-03, -5.68785164e-03, -3.26358809e-04,
       -3.26358809e-04,  2.92204389e-04,  2.92204389e-04, -2.88052784e-03,
       -2.88052784e-03,  2.92204389e-04, -3.26358809e-04,  2.92204389e-04,
       -2.88052784e-03, -2.88052784e-03,  2.80071563e-04, -2.10784188e-04,
       -2.10784188e-04,  2.80071563e-04, -7.97072569e-04, -2.10784188e-04,
       -2.10784188e-04,  2.80071563e-04,  2.80071563e-04, -5.31902505e-03,
       -7.07471680e-03, -5.31902505e-03, -1.68328411e-03, -1.68328411e-03,
       -3.26358809e-04, -5.31902505e-03, -1.68328411e-03, -5.31902505e-03,
       -1.68328411e-03, -3.26358809e-04, -3.26358809e-04,  2.36623391e-04,
        2.33267441e-04,  2.33267441e-04,  2.36623391e-04, -3.26358809e-04,
        3.06763779e-05,  2.73958199e-04,  3.06763779e-05, -1.43380669e-03,
       -1.41828293e-03, -

In [7]:
sol.background.nz

array([ 1.00000000e+00,  4.47213595e-01,  4.47213595e-01,  4.47213595e-01,
        4.47213595e-01,  4.47213595e-01, -4.47213595e-01, -4.47213595e-01,
       -4.47213595e-01, -4.47213595e-01, -4.47213595e-01, -1.00000000e+00,
        8.50650808e-01,  8.50650808e-01,  5.25731112e-01,  8.50650808e-01,
        5.25731112e-01, -8.50650808e-01, -8.50650808e-01, -5.25731112e-01,
       -8.50650808e-01, -5.25731112e-01,  8.50650808e-01,  5.25731112e-01,
        7.19829328e-17,  1.16470832e-16,  0.00000000e+00, -5.25731112e-01,
        0.00000000e+00,  0.00000000e+00, -8.50650808e-01,  7.19829328e-17,
        0.00000000e+00,  5.25731112e-01,  8.50650808e-01,  1.16470832e-16,
        5.25731112e-01, -5.25731112e-01, -8.50650808e-01,  0.00000000e+00,
        0.00000000e+00, -5.25731112e-01,  6.74608925e-01,  7.23606798e-01,
        5.05720923e-01,  9.61938358e-01,  8.94427191e-01,  9.61938358e-01,
        5.05720923e-01,  7.23606798e-01,  6.74608925e-01,  7.23606798e-01,
        5.05720923e-01,  

In [8]:
print_mode_comoving_isotropy_report(sol.modes[114], bg, background_u1=0.0)

Dispersion mode 114 comoving-frame isotropy diagnostics
  omega = 2.3784029440446628e+00 + -8.0953642893460978e-02j
  u0 = 1.0000000000000000e+00
  u1 = 0.0000000000000000e+00
  delta Erad_hat = 1.6679247991900506e-01-1.9796127115514293e-02j
  delta Frad_hat_x = 4.8886239596356587e-02-1.3229164617058642e-02j
  |delta Frad_hat_x| / |delta Erad_hat| = 3.0152208208178621e-01
  RMS relative departure from isotropy = 5.2888527527902385e-01
  Max relative departure from isotropy = 9.1042056372100189e-01
  delta Pxx_hat / delta Erad_hat = 3.3252607254206917e-01 + -2.4582407488242145e-02j


{'u0': 1.0,
 'u1': 0.0,
 'mu_lab': array([ 0.        ,  0.        ,  0.85065081,  0.52573111, -0.52573111,
        -0.85065081,  0.        , -0.85065081, -0.52573111,  0.52573111,
         0.85065081,  0.        ,  0.        , -0.5       , -0.5       ,
         0.5       ,  0.5       , -0.5       ,  0.        , -0.5       ,
         0.5       ,  0.5       , -0.30901699, -0.80901699, -0.80901699,
        -0.30901699, -1.        , -0.80901699, -0.80901699, -0.30901699,
        -0.30901699,  0.80901699,  1.        ,  0.80901699,  0.30901699,
         0.30901699,  0.        ,  0.80901699,  0.30901699,  0.80901699,
         0.30901699,  0.        ,  0.        , -0.26286556, -0.25989191,
        -0.25989191, -0.26286556,  0.        , -0.70204644, -0.52573111,
        -0.70204644,  0.26286556,  0.25989191,  0.25989191,  0.26286556,
         0.70204644,  0.52573111,  0.70204644, -0.70204644, -0.52573111,
        -0.70204644,  0.        , -0.26286556, -0.25989191, -0.25989191,
        -0.262865

# Wave number 2: $p_g >> p_{rad}$

In [9]:
Temperature_choice = 0.1
Erad_choice = 0.01
print("Radiative constant = {}".format(Erad_choice/(Temperature_choice**4.0)))
bg = DispersionBackground.from_parameters(
    rho0=1.0,
    temperature0=Temperature_choice,
    gamma_ad=5.0 / 3.0,
    absorption_opacity=10.0,
    scattering_opacity=10.0,
    erad0=Erad_choice,
    grid=grid,
    arad=Erad_choice/(Temperature_choice**4.0),
    require_thermal_equilibrium=True,
)

sol = solve_dispersion_relation(bg, k=2.0 * np.pi, normalize_to="rho1")
#sol.modes[0].omega

Radiative constant = 99.99999999999999


In [10]:
for i in range(len(sol.modes)):
    mode = sol.modes[i]
    if ( np.abs( np.imag(mode.omega) ) < 8 ):
        print("Wave Id = ", i, "Mode.omega = ", np.real(mode.omega), np.imag(mode.omega) )

Wave Id =  51 Mode.omega =  -2.2917405978371 -0.02223843612298312
Wave Id =  80 Mode.omega =  2.2213141737714693e-15 -0.07765375842863935
Wave Id =  113 Mode.omega =  2.2917405978371144 -0.02223843612297986


In [11]:
mode = sol.modes[113]
mode.omega, mode.rho1, mode.p1, mode.v1, mode.erad1, mode.frad1

((2.2917405978371144-0.02223843612297986j),
 (1-0j),
 (0.16055184724467222-0.003707258346506291j),
 (0.3647418444301513-0.0035393570356060814j),
 (0.022966725332133273+0.0006315001932602536j),
 (0.005013983124944133-0.0018467774725540106j))

In [12]:
np.real(sol.modes[113].intensity1)

array([0.00185905, 0.00185905, 0.00279637, 0.0024823 , 0.00118357,
       0.00078544, 0.00185905, 0.00078544, 0.00118357, 0.0024823 ,
       0.00279637, 0.00185905, 0.00185905, 0.0012162 , 0.0012162 ,
       0.00245465, 0.00245465, 0.0012162 , 0.00185905, 0.0012162 ,
       0.00245465, 0.00245465, 0.00146128, 0.0008347 , 0.0008347 ,
       0.00146128, 0.00061393, 0.0008347 , 0.0008347 , 0.00146128,
       0.00146128, 0.00276004, 0.00291647, 0.00276004, 0.00223876,
       0.00223876, 0.00185905, 0.00276004, 0.00223876, 0.00276004,
       0.00223876, 0.00185905, 0.00185905, 0.00152094, 0.00152479,
       0.00152479, 0.00152094, 0.00185905, 0.00096385, 0.00118357,
       0.00096385, 0.00218409, 0.00218054, 0.00218054, 0.00218409,
       0.00266122, 0.0024823 , 0.00266122, 0.00096385, 0.00118357,
       0.00096385, 0.00185905, 0.00152094, 0.00152479, 0.00152479,
       0.00152094, 0.00185905, 0.00266122, 0.0024823 , 0.00266122,
       0.00218409, 0.00218054, 0.00218054, 0.00218409, 0.00130

In [13]:
np.imag(sol.modes[113].intensity1)

array([ 1.79345719e-04,  1.79345719e-04, -4.70857782e-04, -1.65528564e-04,
        3.03487186e-04,  2.75915218e-04,  1.79345719e-04,  2.75915218e-04,
        3.03487186e-04, -1.65528564e-04, -4.70857782e-04,  1.79345719e-04,
        1.79345719e-04,  3.02494054e-04,  3.02494054e-04, -1.43973692e-04,
       -1.43973692e-04,  3.02494054e-04,  1.79345719e-04,  3.02494054e-04,
       -1.43973692e-04, -1.43973692e-04,  2.79221381e-04,  2.83345974e-04,
        2.83345974e-04,  2.79221381e-04,  2.40876948e-04,  2.83345974e-04,
        2.83345974e-04,  2.79221381e-04,  2.79221381e-04, -4.28694972e-04,
       -6.27887549e-04, -4.28694972e-04,  1.83713771e-06,  1.83713771e-06,
        1.79345719e-04, -4.28694972e-04,  1.83713771e-06, -4.28694972e-04,
        1.83713771e-06,  1.79345719e-04,  1.79345719e-04,  2.69266442e-04,
        2.68565964e-04,  2.68565964e-04,  2.69266442e-04,  1.79345719e-04,
        2.97390167e-04,  3.03487186e-04,  2.97390167e-04,  3.31016427e-05,
        3.50606962e-05,  

# Wave number 3: $p_{rad} \gg p_g$

In [20]:
Temperature_choice = 0.1
Erad_choice = 3
print("Radiative constant = {}".format(Erad_choice/(Temperature_choice**4.0)))
bg = DispersionBackground.from_parameters(
    rho0=1.0,
    temperature0=Temperature_choice,
    gamma_ad=5.0 / 3.0,
    absorption_opacity=10.0,
    scattering_opacity=10.0,
    erad0=Erad_choice,
    grid=grid,
    arad=Erad_choice/(Temperature_choice**4.0),
    require_thermal_equilibrium=True,
)

sol = solve_dispersion_relation(bg, k=2.0 * np.pi, normalize_to="rho1")
#sol.modes[0].omega

Radiative constant = 29999.999999999993


In [15]:
for i in range(len(sol.modes)):
    mode = sol.modes[i]
    if ( np.abs( np.imag(mode.omega) ) < 8 ):
        print("Wave Id = ", i, "Mode.omega = ", np.real(mode.omega), np.imag(mode.omega) )

Wave Id =  35 Mode.omega =  -3.3634301836234517 -0.20277395420173389
Wave Id =  81 Mode.omega =  8.929448790843922e-16 -0.04381889677112962
Wave Id =  129 Mode.omega =  3.363430183623422 -0.20277395420158006


In [16]:
mode = sol.modes[129]
mode.omega, mode.rho1, mode.p1, mode.v1, mode.erad1, mode.frad1

((3.363430183623422-0.20277395420158006j),
 (0.9999999999999999-0j),
 (0.1336044829214556-0.0012243895643073725j),
 (0.5353065394681665-0.03227247714151183j),
 (4.032925850712012-0.13020915455809715j),
 (2.1280425332339448-0.19923695702130564j))

In [17]:
np.real(sol.modes[129].intensity1)

array([ 0.31694586,  0.31694586,  0.75219127,  0.59577558,  0.04575638,
       -0.10208525,  0.31694586, -0.10208525,  0.04575638,  0.59577558,
        0.75219127,  0.31694586,  0.31694586,  0.05824998,  0.05824998,
        0.58263563,  0.58263563,  0.05824998,  0.31694586,  0.05824998,
        0.58263563,  0.58263563,  0.1539711 , -0.08424546, -0.08424546,
        0.1539711 , -0.16320613, -0.08424546, -0.08424546,  0.1539711 ,
        0.1539711 ,  0.73330136,  0.81662034,  0.73330136,  0.48278369,
        0.48278369,  0.31694586,  0.73330136,  0.48278369,  0.73330136,
        0.48278369,  0.31694586,  0.31694586,  0.17779313,  0.17933593,
        0.17933593,  0.17779313,  0.31694586, -0.03686921,  0.04575638,
       -0.03686921,  0.45819472,  0.45660618,  0.45660618,  0.45819472,
        0.68309036,  0.59577558,  0.68309036, -0.03686921,  0.04575638,
       -0.03686921,  0.31694586,  0.17779313,  0.17933593,  0.17933593,
        0.17779313,  0.31694586,  0.68309036,  0.59577558,  0.68

In [18]:
np.imag(sol.modes[129].intensity1)

array([ 0.04270737,  0.04270737, -0.11290524, -0.02569716,  0.02063649,
       -0.02956035,  0.04270737, -0.02956035,  0.02063649, -0.02569716,
       -0.11290524,  0.04270737,  0.04270737,  0.0235669 ,  0.0235669 ,
       -0.02017792, -0.02017792,  0.0235669 ,  0.04270737,  0.0235669 ,
       -0.02017792, -0.02017792,  0.03974045, -0.02189617, -0.02189617,
        0.03974045, -0.05953186, -0.02189617, -0.02189617,  0.03974045,
        0.03974045, -0.1000289 , -0.16271108, -0.1000289 ,  0.01391245,
        0.01391245,  0.04270737, -0.1000289 ,  0.01391245, -0.1000289 ,
        0.01391245,  0.04270737,  0.04270737,  0.04208294,  0.04221194,
        0.04221194,  0.04208294,  0.04270737, -0.00376141,  0.02063649,
       -0.00376141,  0.02029472,  0.02068087,  0.02068087,  0.02029472,
       -0.06914581, -0.02569716, -0.06914581, -0.00376141,  0.02063649,
       -0.00376141,  0.04270737,  0.04208294,  0.04221194,  0.04221194,
        0.04208294,  0.04270737, -0.06914581, -0.02569716, -0.06

# Hydrodynamic only:

In [25]:

grid = make_geodesic_angular_grid(generation=2)

bg = DispersionBackground.from_parameters(
    rho0=1.0,
    temperature0=1.0,
    gamma_ad=5.0 / 3.0,
    absorption_opacity=0.0,
    scattering_opacity=0.0,
    erad0=0.0,
    grid=grid,
    arad=1.0,
)

sol = solve_dispersion_relation(bg, k=2.0 * np.pi, normalize_to="rho1")
#sol.modes[0].omega
#print_mode_comoving_isotropy_report(sol.modes[30], bg, background_u1=0.0)

In [26]:
## We identify the pressure wave by w = +- cs k, with k = 2pi  so omega = 4.335809 ... since cs = 0.69007
for i in range(len(sol.modes)):
    mode = sol.modes[i]
    if ( np.abs( np.imag(mode.omega) ) < 8 ):
        print("Wave Id = ", i, "Mode.omega = ", np.real(mode.omega), np.imag(mode.omega) )

Wave Id =  0 Mode.omega =  -6.283185307179586 0.0
Wave Id =  1 Mode.omega =  -6.044036956040371 0.0
Wave Id =  2 Mode.omega =  -6.044036956040371 0.0
Wave Id =  3 Mode.omega =  -5.975664329483112 0.0
Wave Id =  4 Mode.omega =  -5.975664329483112 0.0
Wave Id =  5 Mode.omega =  -5.975664329483112 0.0
Wave Id =  6 Mode.omega =  -5.975664329483112 0.0
Wave Id =  7 Mode.omega =  -5.420305921117921 0.0
Wave Id =  8 Mode.omega =  -5.420305921117921 0.0
Wave Id =  9 Mode.omega =  -5.420305921117921 0.0
Wave Id =  10 Mode.omega =  -5.420305921117921 0.0
Wave Id =  11 Mode.omega =  -5.344796660577976 0.0
Wave Id =  12 Mode.omega =  -5.344796660577976 0.0
Wave Id =  13 Mode.omega =  -5.344796660577975 0.0
Wave Id =  14 Mode.omega =  -5.344796660577975 0.0
Wave Id =  15 Mode.omega =  -5.0832036923152595 0.0
Wave Id =  16 Mode.omega =  -5.0832036923152595 0.0
Wave Id =  17 Mode.omega =  -5.0832036923152595 0.0
Wave Id =  18 Mode.omega =  -5.0832036923152595 0.0
Wave Id =  19 Mode.omega =  -4.411087

In [27]:
print_mode_comoving_isotropy_report(sol.modes[137], bg, background_u1=0.0)

Dispersion mode 137 comoving-frame isotropy diagnostics
  omega = 4.3358097834505420e+00 + 0.0000000000000000e+00j
  u0 = 1.0000000000000000e+00
  u1 = 0.0000000000000000e+00
  delta Erad_hat = 0.0000000000000000e+00+0.0000000000000000e+00j
  delta Frad_hat_x = 0.0000000000000000e+00+0.0000000000000000e+00j
  |delta Frad_hat_x| / |delta Erad_hat| = nan
  RMS relative departure from isotropy = nan
  Max relative departure from isotropy = nan
  delta Pxx_hat / delta Erad_hat = nan + nanj


{'u0': 1.0,
 'u1': 0.0,
 'mu_lab': array([-0.52573111,  0.52573111, -0.52573111,  0.52573111,  0.        ,
         0.        ,  0.        ,  0.        ,  0.85065081,  0.85065081,
        -0.85065081, -0.85065081, -0.80901699, -0.5       , -0.30901699,
         0.30901699,  0.        ,  0.30901699, -0.30901699, -0.5       ,
        -0.80901699, -1.        ,  0.5       ,  0.80901699, -0.5       ,
         0.        , -0.80901699, -0.80901699,  0.        , -0.5       ,
         0.80901699,  0.5       ,  0.80901699,  0.5       ,  0.30901699,
        -0.30901699,  0.        , -0.30901699,  0.30901699,  0.5       ,
         0.80901699,  1.        , -0.69378048, -0.58778525, -0.43388856,
        -0.70204644, -0.68819096, -0.86266848, -0.16062204, -0.4253254 ,
        -0.25989191, -0.16245985, -0.27326653,  0.16062204,  0.        ,
         0.27326653,  0.16245985,  0.43388856, -0.16245985, -0.43388856,
         0.43388856,  0.16245985, -0.16062204,  0.        ,  0.16062204,
        -0.587785

In [28]:
#Properties of the sound wave:
mode = sol.modes[137]
mode.omega, mode.rho1, mode.ug1, mode.v1, mode.erad1, mode.frad1

((4.335809783450542+0j),
 (1+0j),
 (2.4999999999999982+0j),
 (0.6900655593423536+0j),
 0j,
 0j)